
# Official OpenJDK Java image. Look for the different tagged releases at
# https://hub.docker.com/_/openjdk/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.

stages:
  - build
  - test
  - code-coverage

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Add keyserver for SBT
  - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - mkdir -p /root/.gnupg
  - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
  # Install SBT
  - apt-get update -yqq
  - apt-get install sbt -yqq
  # Log the sbt version
  - sbt sbtVersion

build:
  image: openjdk:8
  script:
    - sbt compile

test:
  image: openjdk:8
  script:
    # Execute your project's tests
    - sbt clean test
  needs:
    ["build"]

code-coverage:
  image: openjdk:8
  script:
    - sbt coverage test coverageReport
  needs:
    ["build"]
  artifacts: 
    reports:
      cobertura:
        - target/scala-2.13/coverage-report/cobertura.xml
    paths:
      - target/scala-2.13/scoverage-report
