
# Official OpenJDK Java image. Look for the different tagged releases at
# https://hub.docker.com/_/openjdk/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: hseeberger/scala-sbt:eclipse-temurin-17.0.1_1.6.1_2.13.8
stages:
  - compilation
  - test
  - code-coverage

build:
  stage: compilation
  script:
    - sbt compile

test:
  stage: test
  script:
    # Execute your project's tests
    - sbt clean test
  needs:
    ["build"]

code-coverage:
  stage: code-coverage
  script:
    - sbt coverage test coverageReport
  needs:
    ["build"]
  artifacts: 
    reports:
      cobertura:
        - target/scala-2.13/coverage-report/cobertura.xml
    paths:
      - target/scala-2.13/scoverage-report
