image: openjdk:8


stages:
  - frontend-tests
  - backend-tests
  - code-coverage

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  ## Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbtVersion


frontend-tests:
  stage: frontend-tests
  script:
    - sbt "testOnly ParserTests"
    - sbt "testOnly SemanticTests"

backend-tests:
  stage: backend-tests
  script:
    - apt-get install gcc-arm-linux-gnueabi -y
    - apt-get install qemu-user -y
    - sbt "testOnly BackendTests"

code-coverage:
  stage: code-coverage
  script:
    - sbt coverage test coverageReport
  needs:
    - frontend-tests
    - backend-tests
  artifacts: 
    reports:
      cobertura:
        - target/scala-2.13/coverage-report/cobertura.xml
    paths:
      - target/scala-2.13/scoverage-report
