
# Official OpenJDK Java image. Look for the different tagged releases at
# https://hub.docker.com/_/openjdk/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: hseeberger/scala-sbt:eclipse-temurin-17.0.1_1.6.1_2.13.8
stages:
  - compilation
  - frontend-tests
  - backend-tests
  - code-coverage

build:
  stage: compilation
  script:
    - sbt compile

test:
  stage: test
  script:
    - sbt "testOnly ParserTests"
    - sbt "testOnly SemanticTests"
  needs:
    - build

backend-tests:
  image: hseeberger/scala-sbt:11.0.9.1_1.4.6_2.13.4
  stage: backend-tests
  script:
    - apt-get install gcc-arm-linux-gnueabi
    - apt-get install qemu-user -y
    - sbt "testOnly BackendTests"
  needs:
    - build

code-coverage:
  stage: code-coverage
  script:
    - sbt coverage test coverageReport
  needs:
    - frontend-tests
    - backend-tests
  artifacts: 
    reports:
      cobertura:
        - target/scala-2.13/coverage-report/cobertura.xml
    paths:
      - target/scala-2.13/scoverage-report
