#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

# puts "TODO: setup this script to call your WACC compiler"

projectName = "compiler"

if ARGV.length == 1
    system("java -jar #{projectName}.jar #{ARGV[0]}")
else
    system("java -jar #{projectName}.jar #{ARGV[0]} #{ARGV[1]}")
end
exit $?.exitstatus
