#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

# puts "TODO: setup this script to call your WACC compiler"

#   The first argument is the filename.
#   The second argument is the number catering to the optimisation technique
#      1 - Constant Evaluation
#      2 - Constant Propagation
#      3 - Control Flow Analysis
#      4 - Peephole Optimisation

projectName = "compiler"

if ARGV.length == 1
    system("java -jar #{projectName}.jar #{ARGV[0]}")
else
    system("java -jar #{projectName}.jar #{ARGV[0]} #{ARGV[1]}")
end
exit $?.exitstatus
